version: '2'
services:
    todo-app:
        image: todo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-postgresql:5432/ToDo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    todo-postgresql:
        extends:
            file: postgresql.yml
            service: todo-postgresql
